version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Running tests...
      - python -m unittest discover

artifacts:
  files:
    - '**/*'
